baseURL = 'https://yxz.is-a.dev/'
languageCode = 'en-us'
title = 'YXZ blog'
theme = 'risotto'

[params]
    author = 'YXZ'
    favicon = '/images/github.png'
    avatar = '/images/avatar.png'
    enableGitalk = false

